<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Account.Infrastructure</RootNamespace>
        <AssemblyName>Account.Infrastructure</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.2.5" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="8.0.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Account.UnitTests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Account.Application\Account.Application.csproj" />
        <ProjectReference Include="..\..\Shared\Contracts\Contracts.csproj" />
        <ProjectReference Include="..\..\Shared\Messaging\Messaging.csproj" />
    </ItemGroup>
</Project>
