<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Account.Application</RootNamespace>
        <AssemblyName>Account.Application</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Account.Infrastructure" />
        <InternalsVisibleTo Include="Account.ArchitectureTests" />
        <InternalsVisibleTo Include="Account.UnitTests" />
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Account.Domain\Account.Domain.csproj" />
    </ItemGroup>
</Project>