<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Identity.Infrastructure</RootNamespace>
        <AssemblyName>Identity.Infrastructure</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.2.5"/>
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="8.0.0"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Identity.Application\Identity.Application.csproj"/>
    </ItemGroup>
</Project>
