<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Identity.Application</RootNamespace>
        <AssemblyName>Identity.Application</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Identity.Infrastructure" />
        <InternalsVisibleTo Include="Identity.ArchitectureTests" />
        <InternalsVisibleTo Include="Identity.UnitTests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Identity.Domain\Identity.Domain.csproj" />
    </ItemGroup>
</Project>
