<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNamespace>Identity.Api</RootNamespace>
        <AssemblyName>Identity.Api</AssemblyName>
        <UserSecretsId>devsu-identity-api</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Identity.Application\Identity.Application.csproj"/>
        <ProjectReference Include="..\Identity.Infrastructure\Identity.Infrastructure.csproj"/>
    </ItemGroup>
</Project>
